### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by paulomfr** [jfbueno/conferidor-organizze#2]
Talvez alterar o método de `window.onload` e colocar um init, seria mais interessante e quanto a cor que tu escolheu, escurecer um pouco hover da linha deve ajudar:

```javascript
(function() {
    'use strict';

    const checkConferenciaClick = function () {
        const parentRow = this.closest('tr')
        parentRow.style.background = this.checked ? '#eaf8fd' : 'transparent'
        parentRow.classList.remove('hover')
    }

    const init = function() {
        const tds = document.querySelectorAll('td.type')

        for(let td of tds) {
            td.querySelector('span').remove()
            const input = document.createElement('input')
            input.type = 'checkbox'
            td.appendChild(input)
            input.onclick = checkConferenciaClick
        }
    }

	init();
})();
```

Isso se a intenção for jogar o código no console (como eu fiz aqui).

**Comment by jfbueno** [comment]
Obrigado pelas dicas. 

Começando pelo início: se eu trocar o `window.load` por essa função não poderei garantir que ela só será executada quando todo o DOM tiver sido carregado, certo?

**Comment by paulomfr** [comment]
@jfbueno se tu vai jogar ela no console para aparecer os checks, você fará isso após o carregamento do DOM. Então não teria a necessidade de verificar se o DOM está carregado.

**Comment by jfbueno** [comment]
@paulomfr Agora que entendi o que você quis dizer... O script, na verdade, foi escrito pra ser utilizado no [tampermonkey](https://www.tampermonkey.net/)/[greasemonkey ](https://addons.mozilla.org/pt-BR/firefox/addon/greasemonkey/)de forma automática. Por isso preciso que o DOM esteja carregado.

**Comment by paulomfr** [comment]
@jfbueno,
Ah! Não conhecia estas extensões, então de fato, é necessário que haja o `window.onload`. rsrs
